//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public Nullable<int> PrePhoneType { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Weixin { get; set; }
        public string OpenId { get; set; }
        public string AvatarUrl { get; set; }
        public Nullable<int> RoleType { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
