//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContextEntities : DbContext
    {
        public DataContextEntities()
            : base("name=DataContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ConfigInfo> ConfigInfos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductAudit> ProductAudits { get; set; }
        public virtual DbSet<ProductMedia> ProductMedias { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<SMSMessageLog> SMSMessageLogs { get; set; }
        public virtual DbSet<T_Address> T_Address { get; set; }
        public virtual DbSet<T_City> T_City { get; set; }
        public virtual DbSet<T_Country> T_Country { get; set; }
        public virtual DbSet<T_District> T_District { get; set; }
        public virtual DbSet<T_Province> T_Province { get; set; }
        public virtual DbSet<TestUser> TestUsers { get; set; }
        public virtual DbSet<ProductPrice> ProductPrices { get; set; }
        public virtual DbSet<Order_Address> Order_Address { get; set; }
        public virtual DbSet<OrderPayRecord> OrderPayRecords { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderReFund> OrderReFunds { get; set; }
    }
}
