//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string OrderSn { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductImagePath { get; set; }
        public Nullable<long> ShopId { get; set; }
        public string ShopName { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> WebPrice { get; set; }
        public Nullable<int> OrderProductAmount { get; set; }
        public Nullable<int> PostType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
