//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Address
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string OrderSn { get; set; }
        public Nullable<long> ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<long> CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public string DistrictName { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> PrePhoneType { get; set; }
        public string TelPhone { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Notes { get; set; }
        public string RealName { get; set; }
        public string PostCode { get; set; }
        public string IdentityCard { get; set; }
        public string IDPhotoNegative { get; set; }
        public string IDPhotoPositive { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
