//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayRecord
    {
        public long Id { get; set; }
        public string OrderSn { get; set; }
        public string NewOrderSn { get; set; }
        public string PartnerOrderId { get; set; }
        public string ChannelOrderId { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public Nullable<decimal> RealFee { get; set; }
        public int PayState { get; set; }
        public Nullable<int> PayChannel { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
    }
}
