//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public long Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> WebPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> DiscountBeginTime { get; set; }
        public Nullable<System.DateTime> DiscountEndTime { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
