//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAudit
    {
        public long Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> AuditStatus { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Remark { get; set; }
        public Nullable<long> OperatorId { get; set; }
        public string OperatorName { get; set; }
    }
}
