//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public long Id { get; set; }
        public string ShopName { get; set; }
        public string Logo { get; set; }
        public Nullable<int> IsSelf { get; set; }
        public Nullable<int> ShopStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ContactsName { get; set; }
        public string ContactsTel { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
