//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionShop.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSMessageLog
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public string SendTo { get; set; }
        public string SendFromGuid { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string Result { get; set; }
        public Nullable<int> SendType { get; set; }
    }
}
